import _AdminLogin from "@/components/admin/_login";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: 'Sign in',
    description: 'Generated by create next app',
}

export default function SigninPage() {
    return (
        <div>
            <_AdminLogin/>
        </div>
    )
}